### ISSUE TITLE
How can I run your code on new data when only providing W? 

### ISSUE THREAD

**Issue by chenynCV** [kongchen1992/compressible-sfm#1]

**Comment by kongchen1992** [comment]
Thanks for your interests and question.  Due to the less success of group sparse dictionary learning, to achieve a global optimal/unique dictionary, we need to remove the noise in W, in other word, to ensure the compressibility of ground truth structure S.  However, such low noise does not always stand in every dataset.  Therefore, we have bunch of code dealing with this problem.  

If your structure S is sufficiently compressible by a dictionary with sufficient incoherence such that the BSDL algorithm utilized here works well, the compressible structure can be recovered purely from W, which is the goal of project actually.

I would like to refer you to my another paper "Structure from Category: A Generic and Prior-less Approach", which deals the same problem, but works more robust than this compressible SFM.  Hopefully, it helps you.

Thanks again,
Chen

**Comment by chenynCV** [comment]
Thank you for your detailed answer.
 You said 'we need to remove the noise in W'. I see in your code 'exp_mocap.m' that you didn't use the origin MoCap data but  run the follwing code to re-generate the data:
`Ri = camera_setup(F, 'continuous');
R = blkdiag(Ri{:});
C = kron(Csharp, eye(3));
Pi = R * C;
S = C * B;
W = R * S;`

But when I just run the following code on the data I generate from MoCap, the result is terrible:
`[Pihat, Bhat, results] = facMethod(W, K, facOpt);
[Rhat, Shat, Rihat] = solveProblem(Pihat, Bhat, [], 0); % NRSfM`

Can't this article deal with this cade directly?

**Comment by kongchen1992** [comment]
1. Since `Csharp` is the clean dictionary code, this step is actually generating a purely compressible structure from the given raw structure.

2. Due to the less success in BSDL community given a signal generated by a dictionary with poor incoherence ( natural S is in this case), the factorization is not globally optimal.  In other word, the uniqueness of BSDL cannot be guaranteed.  Therefore, the result may not look good.  This deficiency is purely caused by `facMethod`.  Hopefully, BSDL community could develop more effective algorithm in the future, such that we could benefit from that.

Thanks,
Chen

**Comment by chenynCV** [comment]
Thank you for your time of explaining for me.
